name: untold_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  states_rebuilder: ^6.0.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

  freezed: ^1.1.1
  lint: ^1.8.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
